sudo: false
language: node_js
node_js:
- '6'
- '8'
- node
os:
- osx
- linux
cache:
  yarn: true
before_install:
- yarn config set spin false
script: yarn cover
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
